export enum DomainErrorCodes {
  LEAD_NAME_REQUIRED = 'LEAD_NAME_REQUIRED',
  LEAD_DOCUMENT_REQUIRED = 'LEAD_DOCUMENT_REQUIRED',
  LEAD_PHONE_REQUIRED = 'LEAD_PHONE_REQUIRED',
  LEAD_ESTIMATED_POTENTIAL_NEGATIVE = 'LEAD_ESTIMATED_POTENTIAL_NEGATIVE',

  RURAL_PROPERTY_LEAD_ID_REQUIRED = 'RURAL_PROPERTY_LEAD_ID_REQUIRED',
  RURAL_PROPERTY_NAME_REQUIRED = 'RURAL_PROPERTY_NAME_REQUIRED',
  RURAL_PROPERTY_TOTAL_AREA_NEGATIVE = 'RURAL_PROPERTY_TOTAL_AREA_NEGATIVE',
  RURAL_PROPERTY_PRODUCTIVE_AREA_NEGATIVE = 'RURAL_PROPERTY_PRODUCTIVE_AREA_NEGATIVE',
  RURAL_PROPERTY_PRODUCTIVE_AREA_EXCEEDS_TOTAL = 'RURAL_PROPERTY_PRODUCTIVE_AREA_EXCEEDS_TOTAL',
  RURAL_PROPERTY_LOCATION_REQUIRED = 'RURAL_PROPERTY_LOCATION_REQUIRED',
  RURAL_PROPERTY_CITY_REQUIRED = 'RURAL_PROPERTY_CITY_REQUIRED',
  RURAL_PROPERTY_STATE_REQUIRED = 'RURAL_PROPERTY_STATE_REQUIRED',

  CULTURE_NAME_REQUIRED = 'CULTURE_NAME_REQUIRED',
  CULTURE_PRICE_NEGATIVE = 'CULTURE_PRICE_NEGATIVE',
  CULTURE_PLANTING_MONTH_INVALID = 'CULTURE_PLANTING_MONTH_INVALID',

  CROP_PRODUCTION_RURAL_PROPERTY_ID_REQUIRED = 'CROP_PRODUCTION_RURAL_PROPERTY_ID_REQUIRED',
  CROP_PRODUCTION_CULTURE_ID_REQUIRED = 'CROP_PRODUCTION_CULTURE_ID_REQUIRED',
  CROP_PRODUCTION_PLANTED_AREA_NEGATIVE = 'CROP_PRODUCTION_PLANTED_AREA_NEGATIVE',
  CROP_PRODUCTION_AREA_EXCEEDS_PRODUCTIVE_AREA = 'CROP_PRODUCTION_AREA_EXCEEDS_PRODUCTIVE_AREA',

  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_UUID = 'INVALID_UUID',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',

  LEAD_NOT_FOUND = 'LEAD_NOT_FOUND',
  RURAL_PROPERTY_NOT_FOUND = 'RURAL_PROPERTY_NOT_FOUND',
  LEAD_ALREADY_EXISTS = 'LEAD_ALREADY_EXISTS',
}
