/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateLeadDto {
  /**
   * Nome completo do lead
   */
  name: string;
  /**
   * CPF ou CNPJ do lead (apenas números ou formatado)
   */
  document: string;
  /**
   * Nome do fornecedor atual (se houver)
   */
  currentSupplier?: string;
  /**
   * Status inicial do lead no funil de vendas
   */
  status?: CreateLeadDto.StatusEnum;
  /**
   * Receita potencial estimada em reais (R$)
   */
  estimatedPotential: number;
  /**
   * Observações ou notas adicionais sobre o lead
   */
  notes?: string;
}
export namespace CreateLeadDto {
  export const StatusEnum = {
    New: 'NEW',
    Contacted: 'CONTACTED',
    Qualified: 'QUALIFIED',
    Converted: 'CONVERTED',
    Lost: 'LOST',
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
}
