/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CropProductionInputDto } from './crop-production-input-dto.model';

export interface CreateRuralPropertyDto {
  /**
   * ID do Lead proprietário associado
   */
  leadId: string;
  /**
   * Nome da propriedade rural
   */
  name: string;
  /**
   * Área total da propriedade em hectares
   */
  totalAreaHectares: number;
  /**
   * Área produtiva da propriedade em hectares
   */
  productiveAreaHectares: number;
  /**
   * Localização geográfica no formato GeoJSON Point
   */
  location: object;
  /**
   * Cidade onde a propriedade está localizada
   */
  city: string;
  /**
   * Estado (UF) da propriedade
   */
  state: string;
  /**
   * Lista de plantações para atualizar (substitui a lista atual)
   */
  cropProductions?: Array<CropProductionInputDto>;
}
