/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CultureDto } from './culture-dto.model';

export interface CropProductionDto {
  /**
   * ID da plantação
   */
  id: string;
  /**
   * ID da cultura vinculada
   */
  cultureId: string;
  /**
   * Área plantada em hectares
   */
  plantedAreaHectares: number;
  /**
   * Dados da cultura (se carregados)
   */
  culture?: CultureDto;
}
