/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CultureDto {
  /**
   * ID da cultura
   */
  id: string;
  /**
   * Nome da cultura
   */
  name: string;
  /**
   * Preço atual da saca/unidade
   */
  currentPrice: number;
  /**
   * Meses de plantio (1-12)
   */
  plantingMonths: Array<number>;
}
