/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DashboardForecastDto {
  /**
   * Total estimated potential value of all active leads (raw sum).
   */
  totalPotential: number;
  /**
   * Count of leads by status.
   */
  countByStatus: object;
}
