/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DashboardPlantingAlertDto {
  /**
   * The name of the culture/crop (e.g., Soja, Milho).
   */
  culture: string;
  /**
   * List of month numbers (1-12) suitable for planting.
   */
  plantingMonths: Array<number>;
  /**
   * Human-readable alert message about the planting window.
   */
  alertMessage: string;
}
