/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardGeoStatsDtoHeatmapInner } from './dashboard-geo-stats-dto-heatmap-inner.model';

export interface DashboardGeoStatsDto {
  /**
   * Total productive area (in hectares) of all rural properties.
   */
  totalAreaRegistered: number;
  /**
   * Total productive area (in hectares) of properties linked to CONVERTED leads.
   */
  totalAreaConverted: number;
  /**
   * Percentage of area converted vs total area registered (0-100).
   */
  penetrationPercentage: number;
  /**
   * Heatmap data points representing lead potential by location.
   */
  heatmap: Array<DashboardGeoStatsDtoHeatmapInner>;
}
