/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DashboardMarketShareDto {
  /**
   * Name of the current input supplier.
   */
  supplier: string;
  /**
   * Percentage of market share for this supplier (0-100).
   */
  sharePercentage: number;
  /**
   * Count of leads associated with this supplier.
   */
  count: number;
}
