/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationMetadata } from './pagination-metadata.model';
import { LeadDto } from './lead-dto.model';

export interface GetLeadsResponseDto {
  metadata: PaginationMetadata;
  data: Array<LeadDto>;
}
