/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LeadScoreDto {
  /**
   * Identificador único do lead (UUID)
   */
  id: string;
  /**
   * Potencial de receita estimado (R$)
   */
  estimatedPotential: number;
  /**
   * Data da última atualização
   */
  updatedAt: string;
}
