/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RuralPropertyDto } from './rural-property-dto.model';

export interface LeadDto {
  /**
   * Identificador único do lead (UUID)
   */
  id: string;
  /**
   * Nome completo do lead
   */
  name: string;
  /**
   * CPF ou CNPJ do lead
   */
  document: string;
  /**
   * Telefone de contato
   */
  phone: string;
  /**
   * Fornecedor atual (opcional)
   */
  currentSupplier?: string | null;
  /**
   * Status atual no funil de vendas
   */
  status: LeadDto.StatusEnum;
  /**
   * Potencial de receita estimado (R$)
   */
  estimatedPotential: number;
  /**
   * Notas e observações
   */
  notes?: string | null;
  /**
   * Data de criação do registro
   */
  createdAt: string;
  /**
   * Data da última atualização
   */
  updatedAt: string;
  /**
   * Lista de propriedades rurais
   */
  properties?: Array<RuralPropertyDto>;
}
export namespace LeadDto {
  export const StatusEnum = {
    New: 'NEW',
    Contacted: 'CONTACTED',
    Qualified: 'QUALIFIED',
    Converted: 'CONVERTED',
    Lost: 'LOST',
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
}
