/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PaginationMetadata {
  /**
   * Total de itens encontrados
   */
  total: number;
  /**
   * Página atual
   */
  page: number;
  /**
   * Itens por página
   */
  limit: number;
  /**
   * Total de páginas
   */
  totalPages: number;
}
