/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PointDto {
  /**
   * BBox
   */
  bbox: Array<number>;
  /**
   * Coordinates
   */
  coordinates: Array<number>;
  /**
   * Type
   */
  type: string;
}
