/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RuralPropertyDto {
  /**
   * Identificador único da propriedade (UUID)
   */
  id: string;
  /**
   * ID do Lead proprietário
   */
  leadId: string;
  /**
   * Nome da propriedade rural
   */
  name: string;
  /**
   * Área total em hectares
   */
  totalAreaHectares: number;
  /**
   * Área produtiva em hectares
   */
  productiveAreaHectares: number;
  /**
   * Localização geográfica (GeoJSON Point)
   */
  location: object;
  /**
   * Cidade da propriedade
   */
  city: string;
  /**
   * Estado (UF)
   */
  state: string;
  /**
   * Data de registro da propriedade
   */
  createdAt: string;
  /**
   * Data da última alteração
   */
  updatedAt: string;
}
