/**
 * TM Digital API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UpdateLeadDto {
  /**
   * Nome completo do lead
   */
  name?: string;
  /**
   * Fornecedor atual do lead
   */
  currentSupplier?: string;
  /**
   * Novo status do lead no funil
   */
  status?: UpdateLeadDto.StatusEnum;
  /**
   * Receita potencial estimada em reais (R$)
   */
  estimatedPotential?: number;
  /**
   * Observações ou notas adicionais
   */
  notes?: string;
}
export namespace UpdateLeadDto {
  export const StatusEnum = {
    New: 'NEW',
    Contacted: 'CONTACTED',
    Qualified: 'QUALIFIED',
    Converted: 'CONVERTED',
    Lost: 'LOST',
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
}
